import { Router, type IRouter } from "express";
import healthRouter from "./v1/health.js";
import categoriesRouter from "./v1/categories.js";
import merchantsRouter from "./v1/merchants.js";
import productsRouter from "./v1/products.js";
import feedRouter from "./v1/feed.js";
import ordersRouter from "./v1/orders.js";
import reviewsRouter from "./v1/reviews.js";
import searchRouter from "./v1/search.js";
import dashboardRouter from "./v1/dashboard.js";
import usersRouter from "./v1/users.js";
import adsRouter from "./v1/ads.js";
import uploadRouter from "./v1/upload.js";

const router: IRouter = Router();
const version = `/${process.env.API_VERSION || "v1"}`;
router.use(version, healthRouter);
router.use(version, categoriesRouter);
router.use(version, merchantsRouter);
router.use(version, productsRouter);
router.use(version, feedRouter);
router.use(version, ordersRouter);
router.use(version, reviewsRouter);
router.use(version, searchRouter);
router.use(version, dashboardRouter);
router.use(version, usersRouter);
router.use(version, adsRouter);
router.use(version, uploadRouter);

export default router;
