/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * FoodHub API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List food categories
 */
export const ListCategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string(),
  image: zod.string().nullish(),
  productCount: zod.number().optional(),
});
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem);

/**
 * @summary List merchants
 */
export const ListMerchantsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  trending: zod.coerce.boolean().optional(),
  search: zod.coerce.string().optional(),
  limit: zod.coerce.number().optional(),
  offset: zod.coerce.number().optional(),
});

export const ListMerchantsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  coverImage: zod.string(),
  profileImage: zod.string(),
  bio: zod.string(),
  rating: zod.number(),
  reviewCount: zod.number().optional(),
  deliveryTime: zod.string(),
  deliveryFee: zod.number(),
  isOpen: zod.boolean(),
  cuisineType: zod.string(),
  address: zod.string().nullish(),
  followersCount: zod.number(),
  isFollowing: zod.boolean(),
  isTrending: zod.boolean().optional(),
  tags: zod.array(zod.string()).optional(),
});
export const ListMerchantsResponse = zod.array(ListMerchantsResponseItem);

/**
 * @summary Get merchant profile
 */
export const GetMerchantParams = zod.object({
  id: zod.coerce.number(),
});

export const GetMerchantResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  coverImage: zod.string(),
  profileImage: zod.string(),
  bio: zod.string(),
  rating: zod.number(),
  reviewCount: zod.number().optional(),
  deliveryTime: zod.string(),
  deliveryFee: zod.number(),
  isOpen: zod.boolean(),
  cuisineType: zod.string(),
  address: zod.string().nullish(),
  followersCount: zod.number(),
  isFollowing: zod.boolean(),
  isTrending: zod.boolean().optional(),
  tags: zod.array(zod.string()).optional(),
});

/**
 * @summary Toggle follow a merchant
 */
export const FollowMerchantParams = zod.object({
  id: zod.coerce.number(),
});

export const FollowMerchantResponse = zod.object({
  isFollowing: zod.boolean(),
  followersCount: zod.number(),
});

/**
 * @summary Get merchant products
 */
export const GetMerchantProductsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetMerchantProductsResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});
export const GetMerchantProductsResponse = zod.array(
  GetMerchantProductsResponseItem,
);

/**
 * @summary Get merchant reviews
 */
export const GetMerchantReviewsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetMerchantReviewsResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  productId: zod.number().nullish(),
  orderId: zod.number().nullish(),
  reviewerName: zod.string(),
  reviewerAvatar: zod.string().nullish(),
  rating: zod.number(),
  comment: zod.string(),
  createdAt: zod.string(),
});
export const GetMerchantReviewsResponse = zod.array(
  GetMerchantReviewsResponseItem,
);

/**
 * @summary Get trending merchants
 */
export const GetTrendingMerchantsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  coverImage: zod.string(),
  profileImage: zod.string(),
  bio: zod.string(),
  rating: zod.number(),
  reviewCount: zod.number().optional(),
  deliveryTime: zod.string(),
  deliveryFee: zod.number(),
  isOpen: zod.boolean(),
  cuisineType: zod.string(),
  address: zod.string().nullish(),
  followersCount: zod.number(),
  isFollowing: zod.boolean(),
  isTrending: zod.boolean().optional(),
  tags: zod.array(zod.string()).optional(),
});
export const GetTrendingMerchantsResponse = zod.array(
  GetTrendingMerchantsResponseItem,
);

/**
 * @summary List all products
 */
export const ListProductsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  search: zod.coerce.string().optional(),
  merchantId: zod.coerce.number().optional(),
  limit: zod.coerce.number().optional(),
  offset: zod.coerce.number().optional(),
});

export const ListProductsResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});
export const ListProductsResponse = zod.array(ListProductsResponseItem);

/**
 * @summary Get product details
 */
export const GetProductParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});

/**
 * @summary Get trending products
 */
export const GetTrendingProductsResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});
export const GetTrendingProductsResponse = zod.array(
  GetTrendingProductsResponseItem,
);

/**
 * @summary Get social food feed
 */
export const GetFeedQueryParams = zod.object({
  limit: zod.coerce.number().optional(),
  offset: zod.coerce.number().optional(),
});

export const GetFeedResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchant: zod.object({
    id: zod.number(),
    name: zod.string(),
    slug: zod.string(),
    coverImage: zod.string(),
    profileImage: zod.string(),
    bio: zod.string(),
    rating: zod.number(),
    reviewCount: zod.number().optional(),
    deliveryTime: zod.string(),
    deliveryFee: zod.number(),
    isOpen: zod.boolean(),
    cuisineType: zod.string(),
    address: zod.string().nullish(),
    followersCount: zod.number(),
    isFollowing: zod.boolean(),
    isTrending: zod.boolean().optional(),
    tags: zod.array(zod.string()).optional(),
  }),
  productId: zod.number().nullish(),
  product: zod.object({}).passthrough().nullish(),
  image: zod.string(),
  video: zod.string().nullish(),
  caption: zod.string(),
  likes: zod.number(),
  comments: zod.number().optional(),
  shares: zod.number().optional(),
  isTrending: zod.boolean(),
  isLiked: zod.boolean(),
  isSaved: zod.boolean(),
  createdAt: zod.string(),
});
export const GetFeedResponse = zod.array(GetFeedResponseItem);

/**
 * @summary Toggle like on a feed post
 */
export const LikeFeedPostParams = zod.object({
  id: zod.coerce.number(),
});

export const LikeFeedPostResponse = zod.object({
  isLiked: zod.boolean(),
  likes: zod.number(),
});

/**
 * @summary Toggle save on a feed post
 */
export const SaveFeedPostParams = zod.object({
  id: zod.coerce.number(),
});

export const SaveFeedPostResponse = zod.object({
  isSaved: zod.boolean(),
});

/**
 * @summary Get merchant story highlights for feed
 */
export const GetFeedStoriesResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchant: zod.object({
    id: zod.number(),
    name: zod.string(),
    slug: zod.string(),
    coverImage: zod.string(),
    profileImage: zod.string(),
    bio: zod.string(),
    rating: zod.number(),
    reviewCount: zod.number().optional(),
    deliveryTime: zod.string(),
    deliveryFee: zod.number(),
    isOpen: zod.boolean(),
    cuisineType: zod.string(),
    address: zod.string().nullish(),
    followersCount: zod.number(),
    isFollowing: zod.boolean(),
    isTrending: zod.boolean().optional(),
    tags: zod.array(zod.string()).optional(),
  }),
  image: zod.string(),
  hasUnviewed: zod.boolean(),
});
export const GetFeedStoriesResponse = zod.array(GetFeedStoriesResponseItem);

/**
 * @summary List orders
 */
export const ListOrdersQueryParams = zod.object({
  status: zod.coerce.string().optional(),
  merchantId: zod.coerce.number().optional(),
});

export const ListOrdersResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  customerId: zod.number().nullish(),
  customerName: zod.string().nullish(),
  customerPhone: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string().nullish(),
      quantity: zod.number(),
      price: zod.number(),
    }),
  ),
  subtotal: zod.number().optional(),
  deliveryFee: zod.number().optional(),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "preparing",
    "ready",
    "delivering",
    "delivered",
    "cancelled",
  ]),
  address: zod.string(),
  paymentMethod: zod.string(),
  promoCode: zod.string().nullish(),
  discount: zod.number().nullish(),
  estimatedDelivery: zod.string().nullish(),
  trackingStage: zod.number().nullish(),
  driverName: zod.string().nullish(),
  driverPhone: zod.string().nullish(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListOrdersResponse = zod.array(ListOrdersResponseItem);

/**
 * @summary Create a new order
 */
export const CreateOrderBody = zod.object({
  merchantId: zod.number(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      quantity: zod.number(),
    }),
  ),
  address: zod.string(),
  paymentMethod: zod.string(),
  promoCode: zod.string().nullish(),
  notes: zod.string().nullish(),
});

/**
 * @summary Get order details and tracking
 */
export const GetOrderParams = zod.object({
  id: zod.coerce.number(),
});

export const GetOrderResponse = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  customerId: zod.number().nullish(),
  customerName: zod.string().nullish(),
  customerPhone: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string().nullish(),
      quantity: zod.number(),
      price: zod.number(),
    }),
  ),
  subtotal: zod.number().optional(),
  deliveryFee: zod.number().optional(),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "preparing",
    "ready",
    "delivering",
    "delivered",
    "cancelled",
  ]),
  address: zod.string(),
  paymentMethod: zod.string(),
  promoCode: zod.string().nullish(),
  discount: zod.number().nullish(),
  estimatedDelivery: zod.string().nullish(),
  trackingStage: zod.number().nullish(),
  driverName: zod.string().nullish(),
  driverPhone: zod.string().nullish(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Update order status
 */
export const UpdateOrderStatusParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateOrderStatusBody = zod.object({
  status: zod.enum([
    "pending",
    "confirmed",
    "preparing",
    "ready",
    "delivering",
    "delivered",
    "cancelled",
  ]),
});

export const UpdateOrderStatusResponse = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  customerId: zod.number().nullish(),
  customerName: zod.string().nullish(),
  customerPhone: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string().nullish(),
      quantity: zod.number(),
      price: zod.number(),
    }),
  ),
  subtotal: zod.number().optional(),
  deliveryFee: zod.number().optional(),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "preparing",
    "ready",
    "delivering",
    "delivered",
    "cancelled",
  ]),
  address: zod.string(),
  paymentMethod: zod.string(),
  promoCode: zod.string().nullish(),
  discount: zod.number().nullish(),
  estimatedDelivery: zod.string().nullish(),
  trackingStage: zod.number().nullish(),
  driverName: zod.string().nullish(),
  driverPhone: zod.string().nullish(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Create a review
 */
export const CreateReviewBody = zod.object({
  merchantId: zod.number(),
  productId: zod.number().nullish(),
  orderId: zod.number().nullish(),
  reviewerName: zod.string(),
  rating: zod.number(),
  comment: zod.string(),
});

/**
 * @summary Search products and merchants
 */
export const SearchQueryParams = zod.object({
  q: zod.coerce.string(),
});

export const SearchResponse = zod.object({
  merchants: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      slug: zod.string(),
      coverImage: zod.string(),
      profileImage: zod.string(),
      bio: zod.string(),
      rating: zod.number(),
      reviewCount: zod.number().optional(),
      deliveryTime: zod.string(),
      deliveryFee: zod.number(),
      isOpen: zod.boolean(),
      cuisineType: zod.string(),
      address: zod.string().nullish(),
      followersCount: zod.number(),
      isFollowing: zod.boolean(),
      isTrending: zod.boolean().optional(),
      tags: zod.array(zod.string()).optional(),
    }),
  ),
  products: zod.array(
    zod.object({
      id: zod.number(),
      merchantId: zod.number(),
      merchantName: zod.string().nullish(),
      name: zod.string(),
      description: zod.string(),
      price: zod.number(),
      discountPrice: zod.number().nullish(),
      image: zod.string(),
      category: zod.string(),
      isAvailable: zod.boolean(),
      stock: zod.number().nullish(),
      ingredients: zod.array(zod.string()).optional(),
      nutritionalInfo: zod.string().nullish(),
      isTrending: zod.boolean().optional(),
      rating: zod.number().nullish(),
      reviewCount: zod.number().nullish(),
    }),
  ),
});

/**
 * @summary Get merchant dashboard stats summary
 */
export const GetDashboardStatsResponse = zod.object({
  totalRevenue: zod.number(),
  todayRevenue: zod.number(),
  todayOrders: zod.number(),
  pendingOrders: zod.number(),
  totalOrders: zod.number(),
  totalCustomers: zod.number(),
  newCustomersThisWeek: zod.number(),
  avgOrderValue: zod.number(),
  growthRate: zod.number(),
});

/**
 * @summary Get revenue data for chart (last 30 days)
 */
export const GetRevenueChartResponseItem = zod.object({
  date: zod.string(),
  revenue: zod.number(),
  orders: zod.number(),
});
export const GetRevenueChartResponse = zod.array(GetRevenueChartResponseItem);

/**
 * @summary Get merchant orders for kanban view
 */
export const GetDashboardOrdersQueryParams = zod.object({
  status: zod.coerce.string().optional(),
});

export const GetDashboardOrdersResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  customerId: zod.number().nullish(),
  customerName: zod.string().nullish(),
  customerPhone: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      productImage: zod.string().nullish(),
      quantity: zod.number(),
      price: zod.number(),
    }),
  ),
  subtotal: zod.number().optional(),
  deliveryFee: zod.number().optional(),
  total: zod.number(),
  status: zod.enum([
    "pending",
    "confirmed",
    "preparing",
    "ready",
    "delivering",
    "delivered",
    "cancelled",
  ]),
  address: zod.string(),
  paymentMethod: zod.string(),
  promoCode: zod.string().nullish(),
  discount: zod.number().nullish(),
  estimatedDelivery: zod.string().nullish(),
  trackingStage: zod.number().nullish(),
  driverName: zod.string().nullish(),
  driverPhone: zod.string().nullish(),
  notes: zod.string().nullish(),
  createdAt: zod.string(),
});
export const GetDashboardOrdersResponse = zod.array(
  GetDashboardOrdersResponseItem,
);

/**
 * @summary Get merchant's own products
 */
export const GetDashboardProductsResponseItem = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});
export const GetDashboardProductsResponse = zod.array(
  GetDashboardProductsResponseItem,
);

/**
 * @summary Create a product
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean().optional(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
});

/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().optional(),
  price: zod.number().optional(),
  discountPrice: zod.number().nullish(),
  image: zod.string().optional(),
  category: zod.string().optional(),
  isAvailable: zod.boolean().optional(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  merchantId: zod.number(),
  merchantName: zod.string().nullish(),
  name: zod.string(),
  description: zod.string(),
  price: zod.number(),
  discountPrice: zod.number().nullish(),
  image: zod.string(),
  category: zod.string(),
  isAvailable: zod.boolean(),
  stock: zod.number().nullish(),
  ingredients: zod.array(zod.string()).optional(),
  nutritionalInfo: zod.string().nullish(),
  isTrending: zod.boolean().optional(),
  rating: zod.number().nullish(),
  reviewCount: zod.number().nullish(),
});

/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Get customer analytics and retention data
 */
export const GetCustomerAnalyticsResponse = zod.object({
  retentionRate: zod.number(),
  repeatBuyerRate: zod.number(),
  totalCustomers: zod.number(),
  newCustomers: zod.number(),
  topOrderTimes: zod.array(
    zod.object({
      hour: zod.number(),
      count: zod.number(),
    }),
  ),
  orderHeatmap: zod.array(
    zod.object({
      day: zod.string(),
      hour: zod.number(),
      count: zod.number(),
    }),
  ),
  demographics: zod
    .array(
      zod.object({
        label: zod.string(),
        value: zod.number(),
      }),
    )
    .optional(),
});

/**
 * @summary Get best-selling products for the merchant
 */
export const GetTopProductsResponseItem = zod.object({
  productId: zod.number(),
  name: zod.string(),
  image: zod.string(),
  totalSold: zod.number(),
  revenue: zod.number(),
  rank: zod.number(),
});
export const GetTopProductsResponse = zod.array(GetTopProductsResponseItem);

/**
 * @summary List merchant promotions
 */
export const ListPromotionsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  type: zod.enum(["percentage", "fixed", "free_delivery", "bogo"]),
  discount: zod.number(),
  code: zod.string().nullish(),
  startDate: zod.string(),
  endDate: zod.string(),
  isActive: zod.boolean(),
  usageCount: zod.number().optional(),
  impressions: zod.number().nullish(),
});
export const ListPromotionsResponse = zod.array(ListPromotionsResponseItem);

/**
 * @summary Create a promotion
 */
export const CreatePromotionBody = zod.object({
  title: zod.string(),
  type: zod.enum(["percentage", "fixed", "free_delivery", "bogo"]),
  discount: zod.number(),
  code: zod.string().nullish(),
  startDate: zod.string(),
  endDate: zod.string(),
  isActive: zod.boolean().optional(),
});
